# Configuration file

# Paths to project structures and templates
paths:
  structs: ~/Drive/Code/project_structs/
  templates: ~/Drive/Code/project_templates/

# The editor command used to open the config file
editor: open

# Which prompter package to use to get the project to generate
# Options:
# (i): typing_filter: https://pypi.org/project/typing-filter/
  # Provides a searchable list: type to filter results
# (ii): inquirer: https://pypi.org/project/inquirer/
  # More robust implementation
prompter: typing_filter

# Token delimiters
tokens:
  # Token for file replacements, e.g. $teaching-preamble.sty
  file: $
  # Token for subprojects, e.g. $$Quizzes$$
  subproject: $$