# Generate a targeted project which could be for research, coding, review of a subject, etc.
- {mp:formatted_name}:
  - $READMEs-project.md: README.md

  - $$Notebooks/Research$$

  - data:
    - raw: []

  - documents: 
    - $READMEs-documents.md: README.md

  - figures:
    - $READMEs-figures.md: README.md

  - manuscript:
    - manuscript.tex
    - preamble.sty
    - $READMEs-manuscript.md: README.md

  - notebooks:
    - $READMEs-notebooks.md: README.md

  - presentations:
    - $READMEs-presentations.md: README.md
    # Placeholder presentation
    - {mp:date}_presentation_title:
      - preamble.sty
      - {mp:date}_presentation_title.tex

  - reports:
    - $READMEs-reports.md: README.md

  # Scripts for the project
  - scripts:
    - $LICENSE
    - $READMEs-scripts.md: README.md

    - _archive:
      - $READMEs-scripts_archive.md: README.md

    - tools:
      - $scripts-config.py: config.py
      - $READMEs-scripts_tools.md: README.md